name: Fetch

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch all branches
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Fetch and parse sheet
        run: |
          bash main.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
